# Generated by Django 3.0.11 on 2020-12-29 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('WAIT', 'Wait for samples'), ('SEQUENCING', 'Sequencing'), ('ANALYSIS', 'Analysis'), ('DONE', 'Finish'), ('ERROR', 'Error'), ('ARCHIVED', 'Archived'), ('AVAILABLE', 'Data available'), ('STOP', 'Stop')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_project_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
