# Generated by Django 3.0.11 on 2021-03-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='studyId',
            field=models.SlugField(max_length=200),
        ),
    ]
