# Generated by Django 3.0.11 on 2021-06-10 06:42

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20210610_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doid',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='pmid',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
