# Generated by Django 3.0.11 on 2021-06-17 08:24

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20210610_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topics',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
