# Generated by Django 3.0.11 on 2021-07-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_article_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team', models.TextField(blank=True, verbose_name='description')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='study',
            old_name='viewer',
            new_name='scope',
        ),
        migrations.AddField(
            model_name='article',
            name='bioRxiv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='bioStudies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pmc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='shorthand',
            field=models.TextField(blank=True, verbose_name='shorthand'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pmid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='as_contributor', to='studies.Contributor'),
        ),
    ]
