# Generated by Django 3.0.11 on 2021-07-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_auto_20210716_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='as_study', to='studies.Contributor'),
        ),
    ]
