# Generated by Django 3.0.11 on 2022-01-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_auto_20211013_1007'),
        ('studies', '0007_auto_20210723_0845'),
    ]

    operations = [
    ]
