# Generated by Django 3.0.11 on 2022-01-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_auto_20220112_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='study_from', to='studies.Article'),
        ),
        migrations.AlterField(
            model_name='study',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='as_study', to='studies.Contributor'),
        ),
        migrations.AlterField(
            model_name='study',
            name='viewer',
            field=models.ManyToManyField(blank=True, related_name='as_study', to='studies.Viewer'),
        ),
    ]
