# Generated by Django 3.0.11 on 2021-03-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biological',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
        migrations.CreateModel(
            name='CellLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
        migrations.CreateModel(
            name='DevStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
    ]
