# Generated by Django 3.0.11 on 2021-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0007_auto_20210617_0824'),
        ('ontologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontologyLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('ontologyID', models.CharField(blank=True, max_length=200, null=True)),
                ('displayLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('as_parent', models.ManyToManyField(blank=True, related_name='_experimentalprocess_as_parent_+', to='ontologies.ExperimentalProcess')),
            ],
        ),
        migrations.CreateModel(
            name='Granularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontologyLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('ontologyID', models.CharField(blank=True, max_length=200, null=True)),
                ('displayLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('as_parent', models.ManyToManyField(blank=True, related_name='_granularity_as_parent_+', to='ontologies.Granularity')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontologyLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('ontologyID', models.CharField(blank=True, max_length=200, null=True)),
                ('displayLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('as_parent', models.ManyToManyField(blank=True, related_name='_keyword_as_parent_+', to='ontologies.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Omics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontologyLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('ontologyID', models.CharField(blank=True, max_length=200, null=True)),
                ('displayLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('as_parent', models.ManyToManyField(blank=True, related_name='_omics_as_parent_+', to='ontologies.Omics')),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontologyLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('ontologyID', models.CharField(blank=True, max_length=200, null=True)),
                ('displayLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('as_parent', models.ManyToManyField(blank=True, related_name='_organ_as_parent_+', to='ontologies.Organ')),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontologyLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('ontologyID', models.CharField(blank=True, max_length=200, null=True)),
                ('displayLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('as_parent', models.ManyToManyField(blank=True, related_name='_pathology_as_parent_+', to='ontologies.Pathology')),
            ],
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontologyLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('ontologyID', models.CharField(blank=True, max_length=200, null=True)),
                ('displayLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('as_parent', models.ManyToManyField(blank=True, related_name='_sequencing_as_parent_+', to='ontologies.Sequencing')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontologyLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('ontologyID', models.CharField(blank=True, max_length=200, null=True)),
                ('displayLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('as_parent', models.ManyToManyField(blank=True, related_name='_topics_as_parent_+', to='ontologies.Topics')),
            ],
        ),
        migrations.DeleteModel(
            name='Biological',
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
        migrations.RemoveField(
            model_name='cellline',
            name='as_children',
        ),
        migrations.RemoveField(
            model_name='cellline',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cellline',
            name='onto_id',
        ),
        migrations.RemoveField(
            model_name='cellline',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='as_children',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='onto_id',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='devstage',
            name='as_children',
        ),
        migrations.RemoveField(
            model_name='devstage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='devstage',
            name='onto_id',
        ),
        migrations.RemoveField(
            model_name='devstage',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='species',
            name='as_children',
        ),
        migrations.RemoveField(
            model_name='species',
            name='name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='onto_id',
        ),
        migrations.RemoveField(
            model_name='species',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='tissue',
            name='as_children',
        ),
        migrations.RemoveField(
            model_name='tissue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tissue',
            name='onto_id',
        ),
        migrations.RemoveField(
            model_name='tissue',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='cellline',
            name='as_parent',
            field=models.ManyToManyField(blank=True, related_name='_cellline_as_parent_+', to='ontologies.CellLine'),
        ),
        migrations.AddField(
            model_name='cellline',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cellline',
            name='displayLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cellline',
            name='ontologyID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cellline',
            name='ontologyLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='as_parent',
            field=models.ManyToManyField(blank=True, related_name='_chemical_as_parent_+', to='ontologies.Chemical'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='displayLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='ontologyID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='ontologyLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devstage',
            name='as_parent',
            field=models.ManyToManyField(blank=True, related_name='_devstage_as_parent_+', to='ontologies.DevStage'),
        ),
        migrations.AddField(
            model_name='devstage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='devstage',
            name='displayLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devstage',
            name='ontologyID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devstage',
            name='ontologyLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='as_parent',
            field=models.ManyToManyField(blank=True, related_name='_species_as_parent_+', to='ontologies.Species'),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='species',
            name='displayLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='ontologyID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='ontologyLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tissue',
            name='as_parent',
            field=models.ManyToManyField(blank=True, related_name='_tissue_as_parent_+', to='ontologies.Tissue'),
        ),
        migrations.AddField(
            model_name='tissue',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tissue',
            name='displayLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tissue',
            name='ontologyID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tissue',
            name='ontologyLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
