# Generated by Django 3.0.11 on 2021-03-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biological',
            name='as_ancestor',
        ),
        migrations.RemoveField(
            model_name='biological',
            name='as_parent',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='as_ancestor',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='as_parent',
        ),
        migrations.RemoveField(
            model_name='cellline',
            name='as_ancestor',
        ),
        migrations.RemoveField(
            model_name='cellline',
            name='as_parent',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='as_ancestor',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='as_parent',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='as_ancestor',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='as_parent',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='as_ancestor',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='as_parent',
        ),
        migrations.RemoveField(
            model_name='species',
            name='as_ancestor',
        ),
        migrations.RemoveField(
            model_name='species',
            name='as_parent',
        ),
        migrations.RemoveField(
            model_name='tissue',
            name='as_ancestor',
        ),
        migrations.RemoveField(
            model_name='tissue',
            name='as_parent',
        ),
        migrations.AddField(
            model_name='biological',
            name='as_children',
            field=models.TextField(blank=True, default='', verbose_name='Children'),
        ),
        migrations.AddField(
            model_name='biological',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='cell',
            name='as_children',
            field=models.TextField(blank=True, default='', verbose_name='Children'),
        ),
        migrations.AddField(
            model_name='cell',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='cellline',
            name='as_children',
            field=models.TextField(blank=True, default='', verbose_name='Children'),
        ),
        migrations.AddField(
            model_name='cellline',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='as_children',
            field=models.TextField(blank=True, default='', verbose_name='Children'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='disease',
            name='as_children',
            field=models.TextField(blank=True, default='', verbose_name='Children'),
        ),
        migrations.AddField(
            model_name='disease',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='as_children',
            field=models.TextField(blank=True, default='', verbose_name='Children'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='species',
            name='as_children',
            field=models.TextField(blank=True, default='', verbose_name='Children'),
        ),
        migrations.AddField(
            model_name='species',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='tissue',
            name='as_children',
            field=models.TextField(blank=True, default='', verbose_name='Children'),
        ),
        migrations.AddField(
            model_name='tissue',
            name='synonyms',
            field=models.TextField(blank=True, default='', verbose_name='Synonyms'),
        ),
        migrations.AlterField(
            model_name='biological',
            name='name',
            field=models.TextField(verbose_name='Ontology name'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='name',
            field=models.TextField(verbose_name='Ontology name'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='name',
            field=models.TextField(verbose_name='Ontology name'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='name',
            field=models.TextField(verbose_name='Ontology name'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.TextField(verbose_name='Ontology name'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.TextField(verbose_name='Ontology name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.TextField(verbose_name='Ontology name'),
        ),
        migrations.AlterField(
            model_name='tissue',
            name='name',
            field=models.TextField(verbose_name='Ontology name'),
        ),
    ]
