# Generated by Django 3.0.11 on 2021-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologies', '0002_auto_20210304_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ontology name')),
                ('synonyms', models.TextField(blank=True, default='', verbose_name='Synonyms')),
                ('onto_id', models.CharField(max_length=200)),
                ('as_children', models.TextField(blank=True, default='', verbose_name='Children')),
            ],
        ),
    ]
